schema_version: '2.0'
profile_selection_criteria: auto
model: nvidia/nemoretriever-table-structure-v1
release: 1.6.0
profiles:
- id: 09231248dff89cf8859d9206931342e468fbddfe469df56334fbe00df7fda1da
  tags:
    backend: triton
    compute_capability: '8.6'
    model_type: tensorrt
    precision: fp16
  workspace:
    files:
      yolox/1/checksums.blake3:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:a10gx1-trt-fp16-ncblfgrrew?file=checksums.blake3
        checksum: blake3:00ad45c69ae9140625363e5e6f2d08b8b74344d5c1e56cbef0a2d0025838b235
      yolox/1/metadata.json:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:a10gx1-trt-fp16-ncblfgrrew?file=metadata.json
        checksum: blake3:f33354fd34d49a4f641f9368f5ca4a158090ba23972404127818072cd1b7344e
      yolox/1/model.plan:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:a10gx1-trt-fp16-ncblfgrrew?file=model.plan
        checksum: blake3:24d1ddc42b974a73f9926374193156228407a9b3c2a9fbe7d995becef0c48649
- id: 0f3b150544da8a053048c1e2a37a282b2c43f09a99253882578d12bc1f2cfca6
  tags:
    backend: triton
    compute_capability: '10.0'
    model_type: tensorrt
    precision: fp16
  workspace:
    files:
      yolox/1/checksums.blake3:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:b200x1-trt-fp16--ce2boy2vw?file=checksums.blake3
        checksum: blake3:86f2f8fe9f9152ae27e3d313d22cbe15bc892aca1769125cc62562537e489010
      yolox/1/metadata.json:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:b200x1-trt-fp16--ce2boy2vw?file=metadata.json
        checksum: blake3:8f47780e55a3915536b11071cd7bab5733225ad77f016c96452ea91e6fed00d0
      yolox/1/model.plan:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:b200x1-trt-fp16--ce2boy2vw?file=model.plan
        checksum: blake3:25c7bb08e6068595537b6dc94da2901a06a540f906321ecd11fa4a49a103a8a1
- id: 58adeef41afa742e753314ae51818e9f017f2c92ba0bfdc01befe6234703a54c
  tags:
    backend: triton
    compute_capability: '9.0'
    model_type: tensorrt
    precision: fp16
  workspace:
    files:
      yolox/1/checksums.blake3:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:h100x1-trt-fp16-lnq0nmbo3g?file=checksums.blake3
        checksum: blake3:567628f4f3607cbc7440674a07a37aca89cdde114a3e908414592e9dc3f61231
      yolox/1/metadata.json:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:h100x1-trt-fp16-lnq0nmbo3g?file=metadata.json
        checksum: blake3:f520de387fe3203f1e4cbbedffeac4ef706e7b59cb21173f9232b5d8d572e6ff
      yolox/1/model.plan:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:h100x1-trt-fp16-lnq0nmbo3g?file=model.plan
        checksum: blake3:0f997cd4c6ad66661800d62de51367b26bb38f2c2b018411ca4f1be3766d5420
- id: b4cc2f8b3d2dcf1afdcafbee8ea694c53aeee642d76f709ed0e79477b68a8dde
  tags:
    backend: triton
    compute_capability: '12.0'
    model_type: tensorrt
    precision: fp16
  workspace:
    files:
      yolox/1/checksums.blake3:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:rtx6000-blackwell-svx1-trt-fp16-unyitj7ofa?file=checksums.blake3
        checksum: blake3:5ade9b986410c0db72eceb042510fe90919653aa565fbac68c51059de7ffc4c5
      yolox/1/metadata.json:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:rtx6000-blackwell-svx1-trt-fp16-unyitj7ofa?file=metadata.json
        checksum: blake3:22bcb8d0e1c2a38c8cfff1a55596bf20f6a80214ba82ed3e8e0ee4a95e2719fe
      yolox/1/model.plan:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:rtx6000-blackwell-svx1-trt-fp16-unyitj7ofa?file=model.plan
        checksum: blake3:6c98d4a4a81612244498d73dbba34a71264b14a7cfdb35eaa94a13bad8a1bc78
- id: bc1487bf0ec3430f17595fff029c1bc50668344c7a30f9e5d64ee061c6e2d5fa
  tags:
    backend: triton
    compute_capability: '8.9'
    model_type: tensorrt
    precision: fp16
  workspace:
    files:
      yolox/1/checksums.blake3:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:l40sx1-trt-fp16-ddoabmkana?file=checksums.blake3
        checksum: blake3:84aebca599bf4fac010428da4c958b192dcdbc77d56554c4a4fbded6fb7dbc57
      yolox/1/metadata.json:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:l40sx1-trt-fp16-ddoabmkana?file=metadata.json
        checksum: blake3:ee557e61b4fb4da3fe600b1c4199d39f7a0d994102d57530155d5cc2b4da5286
      yolox/1/model.plan:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:l40sx1-trt-fp16-ddoabmkana?file=model.plan
        checksum: blake3:546015e1b14c4c5eae408c22b7109cc8d641718c848a4b1d2fbb14a2269ee557
- id: edc693c6fccd68d266622eace04225421e353d7ce31e3b207afc5ff35124127b
  tags:
    backend: triton
    model_type: onnx
    precision: fp16
  workspace:
    files:
      yolox/1/checksums.blake3:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:a100x1-onnx-fp16-l8hnwsbr3g?file=checksums.blake3
        checksum: blake3:68ba920a760b29fa414cd89dc68ca98b4fb7b6a76ef473abb4ecf36d1f0edb3a
      yolox/1/metadata.json:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:a100x1-onnx-fp16-l8hnwsbr3g?file=metadata.json
        checksum: blake3:627c33aa9d0713715c4ebbb379af5fe98b09b808371aca5d6fbb4ebe4f583689
      yolox/1/model.onnx:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:a100x1-onnx-fp16-l8hnwsbr3g?file=model.onnx
        checksum: blake3:62cab0af168a488bceece5913f15a311de94ae432359b4fb6ee4033b6712b5f3
- id: f0fb2f72a66230096c40fc3307872ebb9bce69816cbfc6e2918695ca824bd284
  tags:
    backend: triton
    compute_capability: '8.0'
    model_type: tensorrt
    precision: fp16
  workspace:
    files:
      yolox/1/checksums.blake3:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:a100x1-trt-fp16-jvvssvik-q?file=checksums.blake3
        checksum: blake3:21c264b8a091f854de96df1352f4bb49af6d88ea20134aa1476657c1bda9964b
      yolox/1/metadata.json:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:a100x1-trt-fp16-jvvssvik-q?file=metadata.json
        checksum: blake3:412918869569f752ce8c3a8348484db02f3643de5bf6e932b42e2edcf7c254bb
      yolox/1/model.plan:
        uri: ngc://nim/nvidia/nemoretriever-table-structure-v1:a100x1-trt-fp16-jvvssvik-q?file=model.plan
        checksum: blake3:9a684ff2f031e602a07a4c572cfbfe5347f0dd2e5b41f6dc25ff89aa5e332eaa
