models:
- name: Boltz2
  displayName: Boltz2
  modelHubID: boltz2
  category: Biology Foundation Model
  type: NGC
  description: Boltz-2 NIM is a next-generation structural biology foundation model that shows strong performance for both structure and affinity prediction.
  requireLicense: true
  licenseAgreements:
  - label: Use Policy
    url: https://www.nvidia.com/en-us/agreements/enterprise-software/product-specific-terms-for-ai-products/
  - label: License Agreement
    url: https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-software-license-agreement/
  modelVariants:
  - variantId: Boltz2
    source:
      URL: https://catalog.ngc.nvidia.com/orgs/nim/teams/mit/containers/boltz2
    optimizationProfiles:
    - profileId: nim/mit/boltz2:1.3.0-gpuh100_sm90_v1
      framework: TensorRT-LLM
      displayName: Boltz2 H100x1 SM90 V1 FP16 Trt
      ngcMetadata:
        0901e344383119d8d4a5160d4d63933fd350e6aa92a56b925a77ecc32378d4a5:
          model: mit/boltz2
          release: 1.3.0
          tags:
            feat_lora: 'False'
            gpu: H100
            gpu_device: 2330:10de
            nim_workspace_hash_v1: 41c01d6bb5cc24cc98a2e59b7a367d197951ad5684f03ed939a35c45dbafd514
            number_of_gpus: '1'
            pp: '1'
            precision: fp16
            profile: trt
            sm: '90'
            tp: '1'
            v: '1'
      modelFormat: trt-llm
      spec:
      - key: PROFILE
        value: TRT
      - key: PRECISION
        value: FP16
      - key: GPU
        value: H100
      - key: COUNT
        value: 1
      - key: GPU DEVICE
        value: 2330:10DE
      - key: NIM VERSION
        value: 1.3.0
      - key: DOWNLOAD SIZE
        value: 13GB
      - key: SM
        value: '90'
      - key: V
        value: '1'
    - profileId: nim/mit/boltz2:1.3.0-gpua100_sm80_v1
      framework: TensorRT-LLM
      displayName: Boltz2 A100x1 SM80 V1 FP16 Trt
      ngcMetadata:
        3fbc1c2eb885b24f631f8a1d0c58704cca1c7cf1cd2db4b791c7e6d7201aaa5c:
          model: mit/boltz2
          release: 1.3.0
          tags:
            feat_lora: 'False'
            gpu: A100
            gpu_device: 20b2:10de
            nim_workspace_hash_v1: 1cbe7ff69de2ff435540d9ba81052291e9d9f6fdcd6c580b4db556b5e0adf542
            number_of_gpus: '1'
            pp: '1'
            precision: fp16
            profile: trt
            sm: '80'
            tp: '1'
            v: '1'
      modelFormat: trt-llm
      spec:
      - key: PROFILE
        value: TRT
      - key: PRECISION
        value: FP16
      - key: GPU
        value: A100
      - key: COUNT
        value: 1
      - key: GPU DEVICE
        value: 20B2:10DE
      - key: NIM VERSION
        value: 1.3.0
      - key: DOWNLOAD SIZE
        value: 13GB
      - key: SM
        value: '80'
      - key: V
        value: '1'
    - profileId: nim/mit/boltz2:1.3.0-gpurtx6000_ada_sm86_v1
      framework: TensorRT-LLM
      displayName: Boltz2 RTX6000_ADAx1 SM86 V1 FP16 Trt
      ngcMetadata:
        a49907753de80032ade9659c95ef20be5e93af4166b4451531ecac61247ae4b3:
          model: mit/boltz2
          release: 1.3.0
          tags:
            feat_lora: 'False'
            gpu: RTX6000_ADA
            gpu_device: 26b1:10de
            nim_workspace_hash_v1: 8d2989817b603a609a1da17a59010e28c15dd22b51a047d48596d892ff4a1d1a
            number_of_gpus: '1'
            pp: '1'
            precision: fp16
            profile: trt
            sm: '86'
            tp: '1'
            v: '1'
      modelFormat: trt-llm
      spec:
      - key: PROFILE
        value: TRT
      - key: PRECISION
        value: FP16
      - key: GPU
        value: RTX6000_ADA
      - key: COUNT
        value: 1
      - key: GPU DEVICE
        value: 26B1:10DE
      - key: NIM VERSION
        value: 1.3.0
      - key: DOWNLOAD SIZE
        value: 13GB
      - key: SM
        value: '86'
      - key: V
        value: '1'
    - profileId: nim/mit/boltz2:1.3.0-gpul40s_sm89_v1
      framework: TensorRT-LLM
      displayName: Boltz2 L40Sx1 SM89 V1 FP16 Trt
      ngcMetadata:
        baffed15a6e497b2a6a18437bca323a2f9c42f269d3f733a1b7fba0020eb9b02:
          model: mit/boltz2
          release: 1.3.0
          tags:
            feat_lora: 'False'
            gpu: L40S
            gpu_device: 26b9:10de
            nim_workspace_hash_v1: 41fcfb105bfe999210b6cf66cc28a8ecfaa4e513ca13b7b2616c88cd80094bf5
            number_of_gpus: '1'
            pp: '1'
            precision: fp16
            profile: trt
            sm: '89'
            tp: '1'
            v: '1'
      modelFormat: trt-llm
      spec:
      - key: PROFILE
        value: TRT
      - key: PRECISION
        value: FP16
      - key: GPU
        value: L40S
      - key: COUNT
        value: 1
      - key: GPU DEVICE
        value: 26B9:10DE
      - key: NIM VERSION
        value: 1.3.0
      - key: DOWNLOAD SIZE
        value: 13GB
      - key: SM
        value: '89'
      - key: V
        value: '1'
    - profileId: nim/mit/boltz2:1.3.0-gpub200_sm100_v1
      framework: TensorRT-LLM
      displayName: Boltz2 B200x1 SM100 V1 FP16 Trt
      ngcMetadata:
        ca0fa87fc9c52aea7475339eab9fbcec7637a304b261b4ba4450c085a7af4c4d:
          model: mit/boltz2
          release: 1.3.0
          tags:
            feat_lora: 'False'
            gpu: B200
            gpu_device: 2901:10de
            nim_workspace_hash_v1: 9bf86f1e8426e435b6319e0e0d1b6e0a954aced6b59aaa4ed5075de4a7fc52d0
            number_of_gpus: '1'
            pp: '1'
            precision: fp16
            profile: trt
            sm: '100'
            tp: '1'
            v: '1'
      modelFormat: trt-llm
      spec:
      - key: PROFILE
        value: TRT
      - key: PRECISION
        value: FP16
      - key: GPU
        value: B200
      - key: COUNT
        value: 1
      - key: GPU DEVICE
        value: 2901:10DE
      - key: NIM VERSION
        value: 1.3.0
      - key: DOWNLOAD SIZE
        value: 13GB
      - key: SM
        value: '100'
      - key: V
        value: '1'
    - profileId: nim/mit/boltz2:1.3.0-gpugb200_sm100_v1
      framework: TensorRT-LLM
      displayName: Boltz2 GB200x1 SM100 V1 FP16 Trt
      ngcMetadata:
        f27c6b6a5dc860324bcc06dcc0ae502d9840546188e69238ebf58376d26f0539:
          model: mit/boltz2
          release: 1.3.0
          tags:
            feat_lora: 'False'
            gpu: GB200
            gpu_device: 2941:10de
            nim_workspace_hash_v1: 9b199cebb2c954abbc94f5ebf37b0052988a7aa8987617c9271605d5e2e2f0b5
            number_of_gpus: '1'
            pp: '1'
            precision: fp16
            profile: trt
            sm: '100'
            tp: '1'
            v: '1'
      modelFormat: trt-llm
      spec:
      - key: PROFILE
        value: TRT
      - key: PRECISION
        value: FP16
      - key: GPU
        value: GB200
      - key: COUNT
        value: 1
      - key: GPU DEVICE
        value: 2941:10DE
      - key: NIM VERSION
        value: 1.3.0
      - key: DOWNLOAD SIZE
        value: 13GB
      - key: SM
        value: '100'
      - key: V
        value: '1'
  labels:
  - Biology Foundation Model
  - signed images
  - NSPECT-D4IX-8I2O
  - NVIDIA AI Enterprise Supported
  - NVIDIA NIM
  config:
    architectures:
    - Other
    modelType: NIM
  license: NVIDIA AI Foundation Models Community License
